ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'

urlpatterns = [
    path('add_to_cart/<int:pk>/',views.add_to_cart,name="add_to_cart"),
    path('cart_view',views.cart_view,name="cart_view"),
    path('cart_decrement/<int:p>/',views.cart_decrement,name="cart_decrement"),
    path('remove/<int:p>/',views.remove,name="remove"),
    path('order_form',views.order_form,name="order_form"),
    path('payment_status/<u>',views.payment_status,name="payment_status"),
    path('order_view',views.order_view,name="order_view"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]



if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views

app_name='search'

urlpatterns = [
        path('search/',views.search_products,name="search_products"),


]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name='shop'

urlpatterns = [
    path('', views.category, name="category"),
    path('product/<int:i>',views.all_products,name="product"),
    path('product/<int:i>/',views.product_details,name="product_details"),
    path('register/',views.register,name="register"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User


class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    data_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity * self.product.price


class Order_table(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items = models.IntegerField()
    phone = models.CharField(max_length=30)
    address = models.TextField()
    pin = models.CharField(max_length=30)
    ordered_date = models.DateTimeField(auto_now_add=True)
    order_id = models.CharField(max_length=100, blank=True)
    payment_status = models.CharField(max_length=30, default='pending')
    delivery_status = models.CharField(max_length=30, default='pending')

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    name = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)
    order_id = models.CharField(max_length=100, blank=True)
    razorpay_payment_id = models.CharField(max_length=100, blank=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
import razorpay
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from razorpay import Client
from razorpay.resources import payment
from shop.models import Product
from cart.models import Cart, Payment, Order_table
from django.contrib.auth.models import User


@login_required
def add_to_cart(request, pk):
    p = Product.objects.get(id=pk)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (p.stock > 0):
            cart.quantity += 1
            cart.save()
            p.stock -= 1
            p.save()
    except:
        if (p.stock):
            cart = Cart.objects.create(product=p, user=u, quantity=1)
            cart.save()
            p.stock -= 1
            p.save()
    return redirect('cart:cart_view')


@login_required
def cart_view(request):
    u = request.user
    cart = Cart.objects.filter(user=u)
    total = 0
    for i in cart:
        total = total + i.quantity * i.product.price

    return render(request, 'cart.html', {'cart': cart, 'total': total})


def cart_decrement(request, p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()
        else:
            cart.delete()
            p.stock += 1
            p.save()
    except:
        pass
    return cart_view(request)


def remove(request, p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()
    except:
        pass
    return cart_view(request)


def order_form(request):
    if (request.method == "POST"):
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        pin = request.POST.get('pin')

        u = request.user
        c = Cart.objects.filter(user=u)

        total = 0
        for i in c:
            total = total + (i.quantity * i.product.price)  # total amount
        total = int(total * 100)

        # create razorpay client using our API crendentials
        client = razorpay.Client(auth=('rzp_test_JxkEAhDs0tS7ex', 'eoQ9m3vQ1nvjJ0ZRtYTHCELJ'))

        # create order
        response_payment = client.order.create(dict(amount=total, currency="INR"))
        print(response_payment)
        order_id = response_payment['id']
        order_status = response_payment['status']
        if order_status == "created":
            p = Payment.objects.create(name=u.username, amount=total, order_id=order_id)
            p.save()
            for i in c:
                o = Order_table.objects.create(user=u, product=i.product, address=address, phone=phone, pin=pin,
                                               no_of_items=i.quantity, order_id=order_id)
                o.save()

        response_payment['name'] = u.username
        return render(request, 'payment.html', {'payment': response_payment})

    return render(request, 'orderform.html')


@csrf_exempt
def payment_status(request, u):
    print(request.user.is_authenticated)  # False
    if not request.user.is_authenticated:
        user = User.objects.get(username=u)
        login(request, user)
        print(request.user.is_authenticated)  # True

    if (request.method == "POST"):
        response = request.POST  # response after payment
        # print(response)
        # print(u)

        payment_id = response.get('razorpay_order_id')
        order_id = response.get('razorpay_order_id')
        signature = response.get('razorpay_signature')

        param_dict = {
            'razorpay_order_id': response['razorpay_order_id'],
            'razorpay_payment_id': response['razorpay_payment_id'],
            'razorpay_signature': response['razorpay_signature']
        }
        client = razorpay.Client(auth=('rzp_test_JxkEAhDs0tS7ex', 'eoQ9m3vQ1nvjJ0ZRtYTHCELJ'))
        try:
            status = client.utility.verify_payment_signature(
                param_dict)  # to check the authenticity of razorpay signature
            print(status)

            # after successfull payment
            # retrive a payment record with particular order_id
            ord = Payment.objects.get(order_id=response['razorpay_order_id'])

            ord.razorpay_payment_id = response['razorpay_payment_id']
            ord.paid = True  # edit paid to true
            ord.save()


            u = User.objects.get(username=u)
            # print(u.username)
            c = Cart.objects.filter(user=u)
            # filter the order_table details for particular user with order_id=response['razorpay_order_id']
            o = Order_table.objects.filter(user=u, order_id=response['razorpay_order_id'])

            for i in o:
                i.payment_status = 'paid'  # edit payment status into paid
                i.save()


            c.delete()  # delete the cart items for particular user
            return render(request, 'payment_status.html', {'status': True})

        except:
            return render(request, 'payment_status.html', {'status': False})

    return render(request, 'payment_status.html')


@login_required
def order_view(request):
    u = request.user
    customer = Order_table.objects.filter(user=u, payment_status="paid")
    return render(request, 'orderview.html', {'customer': customer, 'u': u.username})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ecommerce</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<!--logo-->
<div class="logo">
    <h1 class="text-center">Trends</h1>
</div>
<!--    navbar-->
   <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
    <a class="navbar-brand" href="#">My shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
           <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:product' i.id %}">{{i.title}}</a></li>
            {% endfor %}
          </ul>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% if user.is_superuser != True %}
          <li class="nav-item">
              <a href="{% url 'cart:cart_view' %}" style=""><img src="{% static 'images/cart.png' %}" width="30px" height="30px"><sup class="fw-bold" style="color:red;fond-size:15px;text-decoration:none;">{{count}}</sup> </a>
          </li>

          <li class="nav-item">
            <a class="nav-link active fs-6" href="{% url 'cart:order_view' %}">Your Orders</a>
          </li>
          {% endif %}
          {% else %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:register' %}">Register</a>
        </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'shop:login' %}">Login</a></li>
           {% endif %}

          <form class="d-flex" method="post" action="{% url 'search:search_products' %}">
              {% csrf_token %}
        <input class="form-control me-2" type="search" name='q' placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
</nav>
{% block content %}
{% endblock %}
<hr>
<!--footer-->
<footer class="bg-dark text-light text-center">
  <div class="container">
    <p>Copyright &copy;2024 Myshop.All Rights Reserved.</p>
  </div>
</footer>

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center fw-bold mt-5">Shopping Cart</h2>
<div class="container-fluid mt-3">
    <div class="row">
    <div class="col-7">
<table class="table table-bordered">
    <tr><th colspan="6">Cart Items</th></tr>

    {% for i in cart %}
    <tr><td><img src="{{i.product.image.url}}" height="150px" width="150px"></td>
        <td>{{i.product.name}}</td>
        <td><b>Product ID:</b>{{i.product.id}}</td>
        <td><b>Quantity:</b>{{i.quantity}}<br><b>Unit Price:</b>{{i.quantity}}*{{i.product.price}}</td>
        <td>Subtotal:{{i.subtotal}}</td>
        <td>
            {% if i.product.stock > 0 %}
            <a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-circle-plus" style="color:black"></i></a><br>
            <a href="{% url 'cart:cart_decrement' i.product.id %}"><i class="fa-solid fa-circle-minus" style="color:black"></i></a><br>
            <a href="{% url 'cart:remove' i.product.id %}"><i class="fa-solid fa-trash" style="color:black"></i></a>
            {% else %}
            <a href="{% url 'cart:cart_decrement' i.product.id %}"><i class="fa-solid fa-minus" style="color:black"></i></a><br>
            <a href="{% url 'cart:remove' i.product.id %}"><i class="fa-solid fa-trash" style="color:black"></i></a>
        {% endif %}
        </td>
    </tr>{% endfor %}
</table></div>
<div class="col-4">
            <table class="table table-bordered">
                <tr><th colspan="4">Checkout</th></tr>
                <tr><td class="fw-bold">Total Amount:{{total}}</td></tr>
            </table>
            <a href="{% url 'cart:order_form' %}" class="btn_1" style="text-decoration:none;">Place Order</a><br>
    <a href="" class="btn_1" style="text-decoration:none;">Continue Shopping</a>
</div>

{% endblock %}

ecommerce/templates/category.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--banner-->
<div class="container mt-3">
    <img src="{% static 'images/banner.webp' %}" alt="banner_image" style="width:100%; height:500px;">
</div>
<!--description-->
<h2 class="text-center text-dark mt-2">Our Collections</h2>
<p class="text-center text-dark">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!--card-->
<div class="container mt-5">
    <div class="row">
        {% for i in category %}
        <div class="col-md-3 mb-4">
<div class="card" style="width: 15rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="300px" width="100%" alt="...">
  <div class="card-body">

      <h5 class="card-title text-center" style="color: black;">{{i.title}}</h5>

    <a href="{% url 'shop:product' i.id %}" style="position:relative;left:35%" class="btn btn-primary text-center">Shop Now</a>
  </div>
</div></div>{% endfor %}
</div></div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center><h2>LOGIN...</h2>
<form method="post" enctype="multipart/form-data" style="width:75%;">
    {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter Username">
</div>
    <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>

    <div class="mb-3">
        <input type="submit" class="form-control">
    </div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</form></center>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center><h2>ENTER DETAILS</h2>
<form method="post" enctype="multipart/form-data" style="width:70%;">
    {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Phone number</label>
  <input type="text" class="form-control" name="phone" placeholder="Enter phone number">
</div>
    <div class="mb-3">
  <label class="form-label">Delivery Address</label>
  <input type="text" class="form-control" name="address" placeholder="Enter address">
</div>
    <div class="mb-3">
  <label class="form-label">Pin number</label>
  <input type=text" class="form-control" name="pin" placeholder="Enter pin number">
</div>

    <div class="mb-3">
        <input type="submit" class="form-control">
    </div>


</form></center>


{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row" style="margin-top:180ox;">
        <h4 class="text-center fw-bold">Name of Customer:{{u}}</h4>
        {% for i in customer %}
        <div class="col-5">
            <img src="{{i.product.image.url}}" width="60%">
        </div>
        <div class="col-6 p-4" style="align-item:center;">
            <hr class="w-25 border border-2 border-dark mx-auto">
            <h5><b>product Name:</b>{{i.product.name}}</h5>
            <h5><b>product Price:</b>{{i.product.price}}</h5>
            <h5><b>no.of items:</b>{{i.no_of_items}}</h5>
            <h5><b>ordered on:</b>{{i.ordered_date}}</h5>
            <h5><b>delivery status:</b>{{i.delivery_status}}</h5>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
<form action="http://127.0.0.1:8000/cart/payment_status/{{payment.name}}" method="POST">
{% csrf_token %}
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_JxkEAhDs0tS7ex"
    data-amount="{{payment.amount}}"
    data-currency="{{payment.currency}}"
    data-order_id="{{payment.id}}"
    data-buttontext="Pay with Razorpay"
    data-name="Trends"
    data-description="fashionable wears"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="you@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
    </center>
{% endblock %}

ecommerce/templates/payment_status.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if status == True %}
<div class="container">
<h2 style="color:green;margin-left:130px;">Thank you.Your payment was successful</h2></div>

{% else %}
<h2 style="color:red;margin-left:130px;">Your payment is failed.Try again</h2>
{% endif %}

{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br>

    <!--category image as banner-->
<div class="row">
    <img src="{{ main_cate.image.url }}" width="100%"; height="700px">
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center fw-bold">{{main_cate.title}}</h1>
            <p>{{main_cate.desc}}</p>
        </div>
    </div>
</div>

<!--product card-->
<div class="container">
    <div class="row">
        {% for i in pro %}
        <div class="col-md-3 col-6">
<div class="card" style="width: 15rem;">
    <a href="{% url 'shop:product_details' i.id %}"><img src="{{i.image.url}}" class="card-img-top" height="300px" width="100%" alt="..."></a>
  <div class="card-body">
      <h5 class="card-title" style="color: black;">{{i.name}}</h5>
      <p class="card-text">{{i.price}}</p>
  </div>
</div></div>{% endfor %}
</div></div>



{% endblock %}

ecommerce/templates/productdetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-4">
    <div class="row">
        <div class="col-5">
            <img src="{{product.image.url }}" width="100%" height="500px">
        </div>
        <div class="col-6">
            <h2 class="fw-bold">{{product.name}}</h2>
            <h5 class="fw-bold text-danger">price:{{product.price}}</h5>
            <h5>Available Stock:{{product.stock}}</h5>
            <p>Product details:<br>{{product.desc}}</p>

         {% if user.is_superuser == True %}
                {% if product.stock > 0 %}
                <h3 class="text-success">Product in Stock</h3>
                <a style="text-decoration:none" href="{% url 'admin:index' %}" class="btn_1">Add Stock</a>
                {% else %}
                <h3 class="text-success">Out in Stock</h3>
                <a style="text-decoration:none" href="{% url 'admin:index' %}" class="btn_1">Add Stock</a>
                {% endif %}
            {% else %}
                {% if product.stock > 0 %}
                    <a style="text-decoration:none" href="{% url 'cart:add_to_cart' product.id %}" class="btn_1">Add To Cart</a>
                {% else %}
                    <h3 class="text-danger">Out Of Stock</h3>
                {% endif %}
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<form method="post" enctype="multipart/form-data" style="width:75%">
    {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter Username">
</div>
    <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>
    <div class="mb-3">
  <label class="form-label">Confirm_password</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter confirm_password">
</div>
      <div class="mb-3">
  <label class="form-label">Email</label>
  <input type="text" class="form-control" name="e" placeholder="Enter email">
</div>
     <div class="mb-3">
  <label class="form-label">First_name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter first name">
</div>
     <div class="mb-3">
  <label class="form-label">last_name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter last name">
</div>

    <div class="mb-3">
        <input type="submit" class="form-control">
    </div>

</form></center>
{% endblock %}
</body>
</html>

ecommerce/templates/search_products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br>
<center>
    <div class="container-fluid mt-4">
        <h3 class="text-center">You have searched for :<span class="text-success">{{query}}</span> </h3>
    </div>
</center>
<div class="container">
    {% if p %}
    <div class="row">
        {% for i in p %}
        <div class="col-md-3 col-6">
            <div class="card mt-3" style="width: 15rem;">
            <a href="{% url 'shop:product_details' i.id %}"><img src="{{i.image.url}}" class="card-img-top" height="300px" width="100%" alt="..."></a>
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <p class="card-text">{{i.price}}</p>
            </div></div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="row">
        <div class="col-md-12">
            <h4 class="fw-bold text-center">No Search Found.. </h4>
        </div>
    </div>
    {% endif %}
</div>


{% endblock %}